// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqzaboyjS3EI7ukkcDh5rgWiujl9pM4f0',
    appId: '1:838241257183:web:57bd050548bef045b70b6a',
    messagingSenderId: '838241257183',
    projectId: 'fir-flutter-auth-b6f61',
    authDomain: 'fir-flutter-auth-b6f61.firebaseapp.com',
    storageBucket: 'fir-flutter-auth-b6f61.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHOVkeiSM060XyxKRTElia9_VmJrQ0ZII',
    appId: '1:838241257183:android:4cfb2cf74b8067f7b70b6a',
    messagingSenderId: '838241257183',
    projectId: 'fir-flutter-auth-b6f61',
    storageBucket: 'fir-flutter-auth-b6f61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCbTU_vH1Hq4oQdpzvU-9bjtRqat6X2rs',
    appId: '1:838241257183:ios:253ecbf498787d02b70b6a',
    messagingSenderId: '838241257183',
    projectId: 'fir-flutter-auth-b6f61',
    storageBucket: 'fir-flutter-auth-b6f61.appspot.com',
    androidClientId:
        '838241257183-aqcrqhtromtaaok9iqp1g6oduhpnepd5.apps.googleusercontent.com',
    iosClientId:
        '838241257183-4q8rjnfb84p0bbspmjs4ud8qf4u5k9r2.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCbTU_vH1Hq4oQdpzvU-9bjtRqat6X2rs',
    appId: '1:838241257183:ios:253ecbf498787d02b70b6a',
    messagingSenderId: '838241257183',
    projectId: 'fir-flutter-auth-b6f61',
    storageBucket: 'fir-flutter-auth-b6f61.appspot.com',
    androidClientId:
        '838241257183-aqcrqhtromtaaok9iqp1g6oduhpnepd5.apps.googleusercontent.com',
    iosClientId:
        '838241257183-4q8rjnfb84p0bbspmjs4ud8qf4u5k9r2.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthDemo',
  );
}
